[package]
name = "staking"
version = "0.0.0"
upgrade_policy = "compatible"
license = "Apache 2.0"
authors = ["Adam Chudas / Ulam Labs"]

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'devnet'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
std = "0x1"
creator = "_"
